import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Loader2 } from 'lucide-react';
import { useBusiness } from '../business';
import { previewDraft, validateDraft } from '../api';
import {designCopy} from '../designCopy';
export default function DraftForm({kind='partner',className=''}) {
 const {copy,lang,preview,contact}=useBusiness(),design=designCopy[lang],form=useRef(),dialog=useRef(),controller=useRef();
 const [errors,setErrors]=useState({}),[loading,setLoading]=useState(false),[status,setStatus]=useState(''),[draft,setDraft]=useState(null);
 const fields=kind==='partner'?['company','name','email','website','countries']:['name','email'];
 const labels={company:copy.company,name:copy.name,email:kind==='partner'?copy.email:copy.support_email,website:copy.website,countries:copy.countries,volume:copy.volume,methods:copy.required_methods,message:copy.message,topic:copy.support_topic};
 const values={under_1000:copy.volume_small,'1000_10000':copy.volume_medium,'10001_50000':copy.volume_large,over_50000:copy.volume_plus,mobile_wallet:copy.mobile_wallet,other:copy.other_method,delivery:copy.topic_delivery,details:copy.topic_details};
 useEffect(()=>()=>{controller.current?.abort();document.body.style.overflow='';},[]);
 useEffect(()=>{if(draft){dialog.current.showModal();document.body.style.overflow='hidden';dialog.current.querySelector('#edit-draft').focus();}},[draft]);
 useEffect(()=>{const first=Object.keys(errors)[0];if(first)form.current?.querySelector(`[name="${first}"]`)?.focus();},[errors]);
 const close=()=>{dialog.current.close();document.body.style.overflow='';form.current?.querySelector('[type=submit]')?.focus();};
 const submit=async event=>{event.preventDefault();if(loading)return;const data=new FormData(form.current),payload=Object.fromEntries(data);if(kind==='partner')payload.methods=data.getAll('methods');Object.keys(payload).forEach(key=>{if(typeof payload[key]==='string')payload[key]=payload[key].trim();});const failures=validateDraft(kind,payload,copy);setErrors(failures);if(Object.keys(failures).length){setStatus(copy.validation_error);return;}setLoading(true);setStatus(copy.checking);controller.current=new AbortController();try{const result=await previewDraft(kind,payload,controller.current.signal);setDraft(result.draft);setStatus(copy.preview_ready);}catch(error){if(error.name!=='AbortError')setStatus(copy.request_error);}finally{setLoading(false);}};
 const download=()=>{const blob=new Blob([copy.preview_unsent+'\n\n'+JSON.stringify(draft,null,2)],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='hubaal-enquiry-preview.txt';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const keys=event=>{if(event.key==='Escape'){event.preventDefault();close();}if(event.key!=='Tab')return;const buttons=[...dialog.current.querySelectorAll('button')];if(event.shiftKey&&document.activeElement===buttons[0]){event.preventDefault();buttons.at(-1).focus();}else if(!event.shiftKey&&document.activeElement===buttons.at(-1)){event.preventDefault();buttons[0].focus();}};
 const id=name=>`${kind}-${name}`,attrs=name=>({id:id(name),name,required:true,disabled:loading,'aria-invalid':!!errors[name],'aria-describedby':id(name)+'-error'}),error=name=><span className="field-error" id={id(name)+'-error'}>{errors[name]||''}</span>;
 if(!preview)return contact.email?<a href={'mailto:'+contact.email} className="button-primary">{copy.discuss}</a>:<p>{copy.method_condition}</p>;
 return <><form ref={form} id={kind==='partner'?'partner-enquiry':'support-note-form'} data-draft={kind} data-testid="transact-form" onSubmit={submit} noValidate className={'draft-form '+className}><span className="preview-tag mb-6">{copy.draft_label}</span><div className="grid sm:grid-cols-2 gap-x-5">{fields.map(name=><div className={'form-field '+(kind==='partner'&&name==='company'?'sm:col-span-2':'')} key={name}><label htmlFor={id(name)}>{labels[name]}</label><input {...attrs(name)} placeholder={kind==='partner'?design.placeholders[name]:undefined} type={name==='email'?'email':name==='website'?'url':'text'} autoComplete={name==='company'?'organization':['name','email'].includes(name)?name:name==='website'?'url':'off'} minLength={name==='email'?5:name==='website'?8:2} maxLength={({company:160,name:100,email:254,website:500,countries:200})[name]}/>{error(name)}</div>)}<div className="form-field"><label htmlFor={id(kind==='partner'?'volume':'topic')}>{kind==='partner'?copy.volume:copy.support_topic}</label><select {...attrs(kind==='partner'?'volume':'topic')} defaultValue=""><option value="">{kind==='partner'?copy.choose_volume:copy.support_topic}</option>{(kind==='partner'?[['under_1000','volume_small'],['1000_10000','volume_medium'],['10001_50000','volume_large'],['over_50000','volume_plus']]:[['delivery','topic_delivery'],['details','topic_details'],['other','topic_other']]).map(([value,key])=><option key={value} value={value}>{copy[key]}</option>)}</select>{error(kind==='partner'?'volume':'topic')}</div>
 {kind==='partner'&&<fieldset aria-describedby={id('methods')+'-error'} className="form-field"><legend className="form-label">{copy.required_methods}</legend><div className="flex flex-wrap gap-x-5 mt-2">{['mobile_wallet','other'].map(value=><label key={value} className="checkbox-label"><input name="methods" type="checkbox" value={value} disabled={loading} aria-invalid={!!errors.methods}/>{values[value]}</label>)}</div>{error('methods')}</fieldset>}</div>
 <div className="form-field"><label htmlFor={id('message')}>{kind==='partner'?copy.message:copy.support_message}</label><textarea {...attrs('message')} placeholder={kind==='partner'?design.placeholders.message:undefined} rows={kind==='partner'?3:4} minLength="10" maxLength="2000" aria-describedby={id('message')+'-error '+id('note')}/>{error('message')}<p id={id('note')} className="text-xs text-ink-dim leading-relaxed mt-1">{copy.safe_message}</p></div><button type="submit" disabled={loading} className="button-primary w-full justify-center">{loading?<><Loader2 size={18} className="animate-spin"/>{copy.checking}</>:<>{copy.review_enquiry}<ArrowRight size={17}/></>}</button><p className="form-status text-sm mt-4 min-h-6 text-ink-dim" role="status" aria-live="polite">{status}</p></form>
 <dialog ref={dialog} id="draft-dialog" aria-labelledby="draft-heading" className="draft-dialog" onKeyDown={keys} onClose={()=>{document.body.style.overflow='';form.current?.querySelector('[type=submit]')?.focus();}}><span className="preview-tag">{copy.draft_label}</span><h2 id="draft-heading" className="font-display text-3xl mt-5">{copy.review_title}</h2><p className="text-ink-dim mt-4">{copy.preview_unsent}</p><dl id="draft-summary" className="my-6">{Object.entries(draft||{}).map(([key,value])=><div key={key} className="border-t border-stroke py-3"><dt className="text-xs text-ink-dim">{labels[key]}</dt><dd className="text-sm mt-1 whitespace-pre-wrap break-words">{Array.isArray(value)?value.map(v=>values[v]||v).join(', '):['volume','topic'].includes(key)?(key==='topic'&&value==='other'?copy.topic_other:values[value]||value):value}</dd></div>)}</dl><div className="flex flex-wrap gap-3"><button id="edit-draft" type="button" onClick={close} className="button-secondary">{copy.edit}</button><button id="download-draft" type="button" onClick={download} className="button-primary">{copy.download}</button></div></dialog></>;
}
