// Copy for the supplied visual design, kept separate from commercial claims.
export const designCopy = {
  en: {
    headlineStart: 'Where speed,', headlineMiddle: 'security &', headlineAccent: 'simplicity', headlineEnd: 'converge.',
    descriptor: 'HUBAAL EXPRESS — SOMALIA · WORLDWIDE PARTNERS',
    services: 'Services', why: 'Why us', mission: 'Mission', partners: 'Partners',
    explore: 'Explore services', capabilities: 'Our capabilities', whyTitle: 'Why choose us',
    heroText: 'Connect your remittance business to local payouts in Somalia. Clear recipient details, delivery updates, and a payout journey your customers can follow.',
    servicesLabel: 'What we do', servicesTitle: 'We solve money-transfer challenges',
    servicesText: 'Connect your sending business with local payout delivery, recipient guidance, and clear status updates.',
    focusTab: 'Our focus', missionTab: 'Our mission', visionTab: 'Our vision',
    mobileLabel: 'Mobile wallets & payout', mobileTitle: 'Bring home closer, one tap at a time',
    mobileText: 'Connect your remittance service to a local mobile-wallet payout journey. Agree the receiving route, confirm the recipient’s details, and follow the delivery outcome through your partner connection.',
    phoneCardTitle: 'Hubaal Express payouts', phoneCardText: 'A connection from your business to the recipient',
    enquiryLabel: 'Get started today', enquiryTitle: 'Start a partnership.', enquiryTitleEnd: 'Deliver locally.',
    enquiryText: 'Prepare the details for a partner conversation: your business, countries, expected volumes, and the payout routes you need.',
    focusLabel: 'Focus', connectionLabel: 'Connection', connectionText: 'Partner payout integration', guideLabel: 'Guide',
    placeholders: {company: 'Your company name', name: 'Your full name', email: 'you@company.com', website: 'https://your-company.com', countries: 'e.g. Norway, Somalia', message: 'Tell us about your payout requirements'},
  },
  so: {
    headlineStart: 'Halka xawaaraha,', headlineMiddle: 'amniga iyo', headlineAccent: 'fudaydku', headlineEnd: 'ku kulmaan.',
    descriptor: 'HUBAAL EXPRESS — SOOMAALIYA · SHURAAKO CAALAMI AH',
    services: 'Adeegyada', why: 'Maxaa noo dooranaysaa', mission: 'Himilada', partners: 'Shuraakada',
    explore: 'Baro adeegyada', capabilities: 'Awoodahayaga', whyTitle: 'Maxaa noo dooranaysaa',
    heroText: 'Ganacsigaaga xawaaladda ku xir lacag-bixinta maxalliga ah ee Soomaaliya. Faahfaahinta qaataha oo cad, warbixinta gaarsiinta, iyo hab lacag-bixin oo macaamiishaadu la socon karaan.',
    servicesLabel: 'Waxa aan qabanno', servicesTitle: 'Waxaan xallinnaa caqabadaha lacag-dirista',
    servicesText: 'Ganacsigaaga dirista ku xir gaarsiinta lacagta maxalliga ah, tilmaamaha qaataha, iyo warbixin xaaladeed oo cad.',
    focusTab: 'Diiraddayada', missionTab: 'Himiladayada', visionTab: 'Aragtidayada',
    mobileLabel: 'Jeebabka moobilka iyo lacag-bixinta', mobileTitle: 'Guriga u soo dhowee, hal taabasho mar kasta',
    mobileText: 'Adeeggaaga xawaaladda ku xir hab lacag-bixin oo jeebka moobilka maxalliga ah. Ku heshiiya waddada lacag helidda, xaqiiji faahfaahinta qaataha, oo la soco natiijada gaarsiinta adigoo adeegsanaya xiriirka shuraakada.',
    phoneCardTitle: 'Lacag-bixinta Hubaal Express', phoneCardText: 'Xiriir u dhexeeya ganacsigaaga iyo qaataha',
    enquiryLabel: 'Maanta bilow', enquiryTitle: 'Bilow shuraako.', enquiryTitleEnd: 'Lacagta gaarsii.',
    enquiryText: 'Diyaari faahfaahinta wadahadalka shuraakada: ganacsigaaga, waddamada, mugga dirista la filayo, iyo waddooyinka lacag-bixinta aad u baahan tahay.',
    focusLabel: 'Diiradda', connectionLabel: 'Xiriirka', connectionText: 'Isku-xirka lacag-bixinta shuraakada', guideLabel: 'Tilmaame',
    placeholders: {company: 'Magaca shirkaddaada', name: 'Magacaaga oo buuxa', email: 'you@company.com', website: 'https://your-company.com', countries: 'Tusaale: Norway, Soomaaliya', message: 'Nooga sheeg baahida lacag-bixintaada'},
  },
};
