import { useBusiness } from './business';

// Somali remains labelled as preview by the server until human language review.
const somali = {
  'Coverage': 'Goobaha gaarsiinta',
  'About': 'Nagu saabsan',
  'Payout instruction': 'Amarka gaarsiinta',
  'Your platform receives the payout outcome and transaction reference.': 'Nidaamkaagu wuxuu helaa natiijada gaarsiinta iyo tixraaca macaamilka.',
  'A phone used for digital payments': 'Taleefan loo adeegsado lacag-bixinta dijitaalka ah',
  'A woman using her phone at a market': 'Haweeney taleefankeeda ku isticmaalaysa suuq',
  'API': 'API',
  'API integration': 'Isku-xirka API',
  'About Hubaal': 'Ku saabsan Hubaal',
  "Speak with the team handling local delivery, transaction queries and partner support.": "La hadal kooxda fulisa gaarsiinta gudaha, su’aalaha macaamillada iyo taageerada iskaashiga.",
  "The payout team handles delivery queries and partner support.": "Kooxda gaarsiintu waxay qabataa su’aalaha gaarsiinta iyo taageerada iskaashiga.",
  "A clear point of contact for integration, payout queries and operational support.": "Xiriir cad oo loogu talagalay isku-xirka, su’aalaha gaarsiinta lacagta iyo taageerada hawlgalka.",
  "Hubaal processes the instruction and delivers USD to the recipient’s mobile wallet or bank account in Somalia.": "Hubaal waxay farsamaysaa amarka, waxayna USD ku gaarsiisaa jeebka moobilka ama akoonka bangiga ee qaataha gudaha Soomaaliya.",
  'Availability': 'Helitaanka',
  'BANK ACCOUNT': 'AKOON BANGI',
  'Bank Account Payout': 'Gaarsiinta akoon bangi',
  'Bank settlement paperwork': 'Dukumentiyada xisaab-xirka bangiga',
  "For international remittance companies and payment businesses": "Loogu talagalay shirkadaha xawaaladaha caalamiga ah iyo ganacsiyada lacag-bixinta",
  "Hubaal serves international remittance companies and payment businesses. Your platform submits instructions, tracks delivery and receives payout outcomes with transaction references.": "Hubaal waxay u adeegtaa shirkadaha xawaaladaha caalamiga ah iyo ganacsiyada lacag-bixinta. Nidaamkaagu wuxuu gudbiyaa amarada, la socdaa gaarsiinta, wuxuuna helaa natiijooyinka iyo tixraacyada macaamilka.",
  "Process, track and confirm each payout": "Farsamee, la soco oo xaqiiji gaarsiin kasta",
  'CASH PICKUP': 'QAADASHO LACAG CADAAN AH',
  "Partner reporting": "Warbixinta iskaashiga",
  'Cash prepared for pickup': 'Lacag caddaan ah oo qaadasho loo diyaariyey',
  'Channel': 'Habka',
  "Hubaal returns the payout status and transaction references to your platform. Your team tracks each instruction through the API and partner portal.": "Hubaal waxay nidaamkaaga u soo celisaa xaaladda gaarsiinta iyo tixraacyada macaamilka. Kooxdaadu waxay amar kasta kala socotaa API-ga iyo bogga iskaashiga.",
  'Company': 'Shirkadda',
  'Confirmed outcomes': 'Natiijooyin la xaqiijiyey',
  "Hubaal Express delivers USD payouts in Somalia for international remittance companies. We process local delivery to mobile wallets and bank accounts, track each instruction and report the outcome to your platform.": "Hubaal Express waxay gudaha Soomaaliya ku gaarsiisaa USD shirkadaha xawaaladaha caalamiga ah. Waxaan lacagta gaarsiinnaa jeebabka moobilka iyo akoonnada bangiyada, waxaan la soconnaa amar kasta, natiijadana waxaan u soo sheegnaa nidaamkaaga.",
  "Submit payout instructions from your platform.": "Nidaamkaaga ka gudbi amarada gaarsiinta lacagta.",
  'DELIVERED · 14:32 EAT': 'LA GAARSIIYEY · 14:32 EAT',
  'Deliver with Hubaal': 'La gaarsii Hubaal',
  'Delivered': 'La gaarsiiyey',
  'Delivered to the wallet they already trust': 'Ku gaarsii jeebka ay hore u aaminaan',
  'Delivery status': 'Xaaladda gaarsiinta',
  'Delivery status pushed back to your systems.': 'Xaaladda gaarsiinta ayaa loogu soo celiyaa nidaamyadaada.',
  'Direct': 'Toos',
  'Discuss': 'Ka wada hadal',
  'Discuss a partnership': 'Ka wada hadal iskaashi',
  "Deliver USD to recipient accounts at Salaam Bank and Premier Bank. Track each instruction with its transaction reference.": "Ku gaarsii USD akoonnada qaataha ee Salaam Bank iyo Premier Bank. La soco amar kasta adigoo adeegsanaya tixraaciisa macaamilka.",
  "Review payout statuses, delivery outcomes and transaction references in your partner records. Hubaal reports each outcome to your platform.": "Ka eeg xaaladaha gaarsiinta, natiijooyinka iyo tixraacyada macaamillada diiwaannadaada iskaashiga. Hubaal waxay nidaamkaaga u soo sheegtaa natiijo kasta.",
  "Deliver USD to EVC Plus, ZAAD and eDahab wallets. Hubaal processes the payout and returns its outcome to your platform.": "Ku gaarsii USD jeebabka EVC Plus, ZAAD iyo eDahab. Hubaal waxay farsamaysaa gaarsiinta, natiijadana waxay u soo celisaa nidaamkaaga.",
  'Every instruction tracked': 'Amar kasta waa lala socdaa',
  'Example payout activity': 'Tusaalaha hawlaha gaarsiinta',
  'Example payout confirmation · illustrative data': 'Tusaalaha xaqiijinta gaarsiinta · xog tusaale ah',
  'Example payout instruction': 'Tusaalaha amarka gaarsiinta',
  'Explore payout coverage': 'Eeg goobaha gaarsiinta',
  "Local payout processing": "Farsamaynta gaarsiinta gudaha",
  'Follow payout references and recorded statuses through the partner API and portal.': 'Tixraacyada gaarsiinta iyo xaaladaha diiwaangashan kala soco API-ga iyo bogga iskaashiga.',
  'From global money-transfer operators to regional payment platforms — Hubaal is the Somalia leg of your payment chain.': 'Laga bilaabo shirkadaha xawaaladaha caalamiga ah ilaa nidaamyada lacag-bixinta gobolka — Hubaal waa qaybta Soomaaliya ee silsiladdaada lacag-bixinta.',
  'From payout instruction to delivered funds': 'Laga bilaabo amarka gaarsiinta ilaa lacagta la gaarsiiyo',
  'HB-774201': 'HB-774201',
  'HUBAAL · SOMALIA · WORLDWIDE · PAYOUT NETWORK ·': 'HUBAAL · SOOMAALIYA · CAALAMKA · SHABAKADDA GAARSIINTA ·',
  'Hands holding a mobile phone': 'Gacmo haya taleefan moobil ah',
  'How it works': 'Sida ay u shaqayso',
  "Hubaal Express delivers USD payouts in Somalia for international remittance companies and payment businesses. We handle local delivery to mobile wallets and bank accounts, including EVC Plus, ZAAD, eDahab, Salaam Bank and Premier Bank.": "Hubaal Express waxay gudaha Soomaaliya ku gaarsiisaa USD shirkadaha xawaaladaha caalamiga ah iyo ganacsiyada lacag-bixinta. Waxaan fulinnaa gaarsiinta gudaha ee jeebabka moobilka iyo akoonnada bangiyada, oo ay ku jiraan EVC Plus, ZAAD, eDahab, Salaam Bank iyo Premier Bank.",
  'Hubaal processes local delivery': 'Hubaal waxay fulisaa gaarsiinta gudaha',
  'Hubaal — Somalia payout network': 'Hubaal — shabakadda gaarsiinta Soomaaliya',
  'Illustrative data': 'Xog tusaale ah',
  "Example data": "Xog tusaale ah",
  "Hubaal delivers recipient payouts in USD through Somali mobile wallets and bank accounts.": "Hubaal waxay lacagta qaataha USD ahaan ugu gaarsiisaa jeebabka moobilka iyo akoonnada bangiyada Soomaaliya.",
  'Integration': 'Isku-xirka',
  'Integration & operations': 'Isku-xirka iyo hawlgalka',
  "Transaction references and payout records give your team a clear view of each instruction.": "Tixraacyada macaamillada iyo diiwaannada gaarsiintu waxay kooxdaada si cad u tusaan amar kasta.",
  "USD payouts to recipients in Somalia": "Gaarsiinta USD ee qaataha gudaha Soomaaliya",
  'Network': 'Shabakadda',
  "Your platform submits the payout instruction. Hubaal handles local delivery and returns the payout outcome with transaction references, giving your team a clear record of each instruction.": "Nidaamkaagu wuxuu gudbiyaa amarka gaarsiinta lacagta. Hubaal waxay fulisaa gaarsiinta gudaha, waxayna soo celisaa natiijada iyo tixraacyada macaamilka, si kooxdaadu u hesho diiwaan cad oo amar kasta ah.",
  'Overseas remittance companies & payment businesses': 'Shirkadaha xawaaladaha iyo lacag-bixinta ee dibadda',
  "PARTNER OPERATIONS": "HAWLAHA ISKAASHIGA",
  'Partner support desk': 'Xafiiska taageerada iskaashiga',
  'Partner with Hubaal': 'La shaqee Hubaal',
  'Partnership enquiry': 'Weydiin iskaashi',
  'Payout confirmed': 'Gaarsiinta waa la xaqiijiyey',
  'Payout coverage': 'Goobaha gaarsiinta',
  'Payout coverage — wallets, banks and counters': 'Goobaha gaarsiinta — jeebab, bangiyo iyo xafiisyo',
  'Payout instructions, references and status updates.': 'Amarada gaarsiinta, tixraacyada iyo cusboonaysiinta xaaladda.',
  'Pending': 'Sugaya',
  "Hubaal delivers USD to the recipient’s mobile wallet or bank account in Somalia. Your platform receives the payout outcome and transaction reference.": "Hubaal waxay USD ku gaarsiisaa jeebka moobilka ama akoonka bangiga qaataha gudaha Soomaaliya. Nidaamkaagu wuxuu helaa natiijada gaarsiinta iyo tixraaca macaamilka.",
  "Payout reporting": "Warbixinta gaarsiinta lacagta",
  'Receiving channel': 'Habka qaadashada',
  'Receiving currency': 'Lacagta la qaadanayo',
  'Recipient receives': 'Qaatahu wuxuu helayaa',
  'Recorded statuses and references keep delivery outcomes visible, including instructions that need manual review.': 'Xaaladaha iyo tixraacyada diiwaangashan waxay muujiyaan natiijooyinka gaarsiinta, oo ay ku jiraan amarada u baahan dib-u-eegis gacanta ah.',
  'Reference': 'Tixraaca',
  'Send the recipient details, channel and amount through the API or partner portal — with your own transaction reference attached.': 'Ku dir faahfaahinta qaataha, habka iyo qadarka API-ga ama bogga iskaashiga — kuna dar tixraaca macaamilkaaga.',
  'Somalia': 'Soomaaliya',
  'Start a partnership': 'Bilow iskaashi',
  'Start delivering with Hubaal': 'Ku bilow gaarsiinta Hubaal',
  "Hubaal delivers USD through Somali mobile wallets and bank accounts. We confirm payout outcomes and report them to the originating partner.": "Hubaal waxay USD ku gaarsiisaa jeebabka moobilka iyo akoonnada bangiyada Soomaaliya. Waxaan xaqiijinnaa natiijooyinka gaarsiinta, waxaana u soo sheegnaa la-hawlgalaha dirista.",
  'Status': 'Xaaladda',
  'Status returned on every payout instruction': 'Xaalad loo soo celiyo amar kasta oo gaarsiin ah',
  'Status tracking & callbacks': 'La socodka xaaladda iyo ogeysiisyada',
  "Hubaal processes payout instructions and tracks local delivery to the recipient’s wallet or bank account.": "Hubaal waxay farsamaysaa amarada gaarsiinta lacagta, waxayna la socotaa gaarsiinta gudaha ee jeebka ama akoonka bangiga qaataha.",
  'Submit the payout instruction': 'Gudbi amarka gaarsiinta',
  "Speak directly with our payout team": "Si toos ah ula hadal kooxdayada gaarsiinta lacagta",
  "Discuss your Somalia payout requirements with our operations team. Share your receiving channels, transaction volumes and integration needs.": "Kooxdayada hawlgalka kala hadal baahiyahaaga gaarsiinta Soomaaliya. La wadaag hababka qaadashada, tirada macaamillada iyo baahiyaha isku-xirka.",
  "The company behind your Somalia payouts": "Shirkadda ka dambaysa gaarsiinta lacagtaada Soomaaliya",
  'The outcome comes back to you': 'Natiijada ayaa laguu soo celinayaa',
  'The person at the end of the payment chain': 'Qofka ku jira dhammaadka silsiladda lacag-bixinta',
  'The receiving experience': 'Khibradda qaadashada',
  "Contact the payout team for channel availability and operating hours.": "Kala xiriir kooxda gaarsiinta helitaanka hababka iyo saacadaha shaqada.",
  'To agree': 'Lagu heshiinayo',
  "Contact operations": "La xiriir hawlgalka",
  'Transaction references': 'Tixraacyada macaamillada',
  "Clear payout records": "Diiwaanno gaarsiin oo cad",
  'Two friends laughing while checking funds on a phone': 'Laba saaxiib oo taleefan eegaya iyagoo qosol wadaagaya',
  'Wallet Payout': 'Gaarsiinta jeebka moobilka',
  'What we deliver': 'Waxa aan gaarsiino',
  'Where you deliver': 'Goobaha aad gaarsiiso',
  'Who we serve': 'Cidda aan u adeegno',
  'Why remittance companies choose Hubaal': 'Sababta shirkadaha xawaaladuhu u doortaan Hubaal',
  "Review payout records and reconcile delivery outcomes.": "Dib u eeg diiwaannada gaarsiinta oo isu waafaji natiijooyinka.",
  'Your local payout': 'Gaarsiinta lacagta gudaha',
  'Your own reference travels with every instruction.': 'Tixraacaaga ayaa la socda amar kasta.',
  'partner in': 'iskaashi ku leh',
  "Discuss your Somalia payout requirements with the team handling local delivery, transaction queries and partner support.": "Kooxda fulisa gaarsiinta gudaha, su’aalaha macaamillada iyo taageerada iskaashiga kala hadal baahiyahaaga gaarsiinta Soomaaliya.",
  "USD payouts in Somalia": "Gaarsiinta USD gudaha Soomaaliya"
};
export function useNewCopy() {
  const {
    lang
  } = useBusiness();
  return text => lang === 'so' ? somali[text] ?? text : text;
}
